### PR TITLE
Fix parseIsTaskEvent

### LINKED ISSUE #165: Support eventStatus and taskStatus keywords without the eventType keyword
If possible.

Related to #163 and #164

### PR DESCRIPTION
**Pull request by louietyj**
Fixes #165

### CODE REVIEW

File: src/main/java/seedu/todo/controllers/concerns/CalendarItemFilter.java [hunk 1]
```diff
@@ -44,18 +45,53 @@
...
-            return new boolean[] { true, true };
-        } else if (parsedResult.get("eventType")[0].equals("task")
-                || parsedResult.get("eventType")[0].equals("tasks")) {
-            return new boolean[] { true, false };
+            eventType = parsedResult.get("eventType")[0];
+        }
+        boolean taskStatusPresent = parsedResult.get("taskStatus") == null;
+        boolean eventStatusPresent = parsedResult.get("eventStatus") == null;
+
+        // Singularize eventType
```
Comment (irvinlim) [inline src/main/java/seedu/todo/controllers/concerns/CalendarItemFilter.java]: Maybe move this into the else block, then no need to check if null

**Review by irvinlim — APPROVED** [review]
