### PR TITLE
Fixing complete/incomplete for List Controller

### LINKED ISSUE #113: Bug with list complete/incomplete
The behaviour for `list complete` vs `list task complete` is different - I'm seeing events in `list complete`.

We should make both of them behave the same way.

### PR DESCRIPTION
**Pull request by ChaseTiong**
fixes #113 

Fixed as suggested

### CODE REVIEW

File: src/main/java/seedu/todo/controllers/ListController.java [hunk 1]
```diff
@@ -206,31 +221,42 @@ private void displayErrorMessage(String input, boolean listAll, boolean listAllS
      *            String input by the user, to display for error message                                            
      */
     private void setupView(boolean isTask, boolean listAll, boolean isCompleted,
```
Comment (irvinlim) [inline src/main/java/seedu/todo/controllers/ListController.java:223]: Isn't this method way too complex and big already, considering it only passes the work onto other methods

**Review by irvinlim — APPROVED** [review]
ok for now

File: src/main/java/seedu/todo/controllers/ListController.java (hunk 1 above)
Comment (ChaseTiong) [reply src/main/java/seedu/todo/controllers/ListController.java:223]: will fix it again
